queue_score_recalculator_job:
  cron: "0 2 * * *"
  persist: true # to see in resque-web interface (https://github.com/resque/resque-scheduler/issues/541#issuecomment-218894599) 
  class: "QueueScoreRecalculatorJob"
  queue: nightly_score_recalculator
  description: "This job triggers a score recalculation job for every student \
    belonging to an active course."
